In [39]:
class myLR:
    def __init__(self):
        self.m=None
        self.b=None

    def fit(self, X_train,y_train):
        #print(X_train.shape)
        num=0
        den=0
    
        for i in range(X_train.shape[0]):
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))
       
        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)  
         
    def predict(self, X_test):
        print(X_test)
        return self.m*X_test+self.b

In [40]:
import numpy as np
import pandas as pd

In [41]:
df=pd.read_csv('placement.csv')

In [42]:
df.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [43]:
X=df.iloc[:,0].values
y=df.iloc[:,1].values

In [44]:
X

array([6.89, 5.12, 7.82, 7.42, 6.94, 7.89, 6.73, 6.75, 6.09, 8.31, 5.32,
       6.61, 8.94, 6.93, 7.73, 7.25, 6.84, 5.38, 6.94])

In [45]:
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98])

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [47]:
X_train.shape

(15,)

In [48]:
lr=myLR()

In [49]:
lr.fit(X_train,y_train)

0.49513785623297796
-0.6392610314300495


In [50]:
X_train.shape[0]

15

In [51]:
X_train[0]

np.float64(5.32)

In [52]:
X_train

array([5.32, 7.89, 7.42, 5.12, 8.94, 6.75, 5.38, 6.84, 7.82, 6.61, 6.73,
       6.94, 6.93, 7.25, 6.09])

In [53]:
X_train.mean()

np.float64(6.8020000000000005)

In [54]:
X_test[0]

np.float64(8.31)

In [57]:
print(lr.predict(X_test[0]))

8.31
3.475334553865997
